### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by christre42** [christre42/Applikasjonsutvikling.github.io#25]
I <form> ved registrering av ny bruker har jeg lagt <label> både rundt og forran <input>. Mitt spørsmål er: Hva er best/riktig?

**Comment by StaaleA** [comment]
Hakkje peiling :o

**Comment by christre42** [comment]
Elendig svar!!

**Comment by christre42** [comment]
Ser nå at deler av spørsmålet er borte ettersom jeg brukte html tags.. Urutt..

**Comment by StaaleA** [comment]
ga ikke mye mening nei...

**Comment by christre42** [comment]
Det mente var:

I formen for registrering av bruker (passord.php) har jeg brukt label for å skrive teksten før input. Men noen steder har jeg avsluttet label ETTER input, mens andre steder er den avsluttet FØR label. Ka e riktig, og ka e feil? 

Vet ikke om det har noe å si engang

**Comment by StaaleA** [comment]
Tror ikke det er noe riktig eller galt her..Hovedforskjellen er vel hvis du tar label rundt både tekst og input så merker du input ved å trykke på teksten... Kan jo kanskje være greit? Iallefall greit å gjøre det likt...

**Comment by christre42** [comment]
Ja, så lenge vi gjør det likt er det nok greit.
