### ISSUE TITLE
Navn på funksjon

### ISSUE THREAD

**Issue by christre42** [christre42/Applikasjonsutvikling.github.io#26]
## sjekkAdminSessionID()

Vi skal ha en felles funksjon som sjekker om brukeren har tilgang til beskyttede sider, men ville bare påpeke at jeg syns navnet er litt misvisende. Ser jo ut som du skal få returnert hvem som er logget inn, men den gir jo kun true/false. 

> funksjonsnavn må være opplagt for usmarte lærere!

Så stemmer for at vi kan gjøre om navnet til **sjekk_rettigheter()**
Noen andre meninger? 

Men om det skal gjøre så må du gjøre det @StaaleA , regner med at mye har skjedd på grenen din.

Er altså snakk om **function.php** om noen lurte.

**Comment by StaaleA** [comment]
Jeg er helt enig, og så det selv i går når jeg fiksa rettigheter på vis_brukere.php, men på grunn av tidsmangel så gjorde jeg ikke noe med det. Har også laget et funksjon som heter `sjekkIspreppSessionID()` som er helt lik, men den sjekker om det er en isprepper som har logget inn. På samme måte som at `sjekkAdminSessionID()` sjekker om det er en admin som har logget inn.

Kan det være mulig å lage en funksjon som fungerer på denne måte:

`sjekk_rettigheter(admin);`
`sjekk_rettigheter(isprepp);`

I think so....

**Comment by christre42** [comment]
Men trenger vi å returnere *hvem* som er logget inn? Ettersom vi setter $_SESSION['brukertype'] når vi logger inn? 

sjekk_rettigheter kan vel kanskje se slik ut?:

    if (!brukertype == "") {
        // Brukertype er satt
        return brukertype
        return true 
    else // brukertype er ikke satt, altså ingen rettigheter
        return false
    }

Bare så vi ikke gjør det samme på to steder nå

**Comment by StaaleA** [comment]
Må jo sjekke om det er admin eller isprepp som er logget inn...

**Comment by christre42** [comment]
Nå detter jeg ut.. :stuck_out_tongue:  Tror du overtar;)

**Comment by StaaleA** [comment]
Du skal ha for initiativet... ;)

Poenget er at brukere som logger inn som isprepper ikke skal ha samme rettigheter som brukere som er admin. (doh) og derfor så kan en ikke bare sjekke om brukertype er satt (kunne jo like gjerne sjekket om brukernavn er satt da... en må sjekke opp mot databasen hva slags brukertype brukeren har...

**Comment by christre42** [comment]
nei det kom litt dårlig frem..:

    if brukertype = admin then... 
    elseif brukertype = isprepp then...
    else brukertype = "" then fuck off...

Må bli noe sånt da? :stuck_out_tongue:

**Comment by StaaleA** [comment]
japp, noe sånt ;)

**Comment by christre42** [comment]
Nå følte jeg meg som lasse..
