### ISSUE TITLE
Kryptering av passord ved innlogging

### ISSUE THREAD

**Issue by christre42** [christre42/Applikasjonsutvikling.github.io#27]
## Viktig: Vi må huske å kryptere passordet ved innlogging!

Så langt har vi ikke gjort dette, ettersom vi har lagt inn brukere i basen som ikke har et kryptert passord, og vi vil jo kunne logge inn mens vi tester. Men hvis registrer_bruker.php fungerer, og vi nå kan legge til nye brukere og kryptere passordene deres. Da må vi også legge det inn ved logginn.php!

Altså @StaaleA , vi må legge inn følgende før vi utfører spørringen i `logginn.php`:

    $passord = KrypterPassord($passord);

**Comment by StaaleA** [comment]
Føler dette er noe for scrum-tavla???? Issues på gitHub bør fremover inneholde referanse til issue på inf.myjetbrains.com. Takk.

**Comment by StaaleA** [comment]
Nå skal jeg sloss. Ser på det senere ikveld :)

**Comment by christre42** [comment]
To separate systemer, dont like.. Skulle vært en integrert Scrum-løsning i Github!
