### ISSUE TITLE
Feil brukernavn eller passord

### ISSUE THREAD

**Issue by christre42** [christre42/Applikasjonsutvikling.github.io#28]
## Hva tastet jeg feil? Tilbakemelding
Kom på at vi bør kanskje si i fra til brukeren om han taster feil brukernavn eller feil passord?
Akkurat nå sjekker vi kun mot begge deler på en gang, og vi vet ikke hvilken av de to som er feil. Men dette trenger vi ikke løse på del 2, men kan være noe å tenkte på til del 3.

**Comment by StaaleA** [comment]
Ja, kanskje, men det er ikke alltid det er vanlig å få beskjed om det..."litt" enklere for "hackere" da de vet at de har en av to riktig... ;) Men vi kan ta det opp til diskusjon---

**Comment by christre42** [comment]
Jupp, tar en diskusjon senere
