### ISSUE TITLE
Legg til brukernavn

### ISSUE THREAD

**Issue by christre42** [christre42/Applikasjonsutvikling.github.io#30]
## registrer_bruker.php
Når vi legger til ny bruker står det i oppgaven at admin skal legge inn `epost, fnavn, enavn og brukertype (valgmeny)`, men det står ingenting om `brukernavn`. Og det står heller ingen ting om at det skal opprettes automatisk. Hvordan tolker dere dette? Jeg mener at det kun er slurv og at det er klart at admin skal legge inn det selv. 

Er kun en fillesak, men vi bør være klar over det, ettersom det ikke var nevnt noe om det i teksten.

**Comment by StaaleA** [comment]
Ja, han var vag på dette i timen også, og forstod det sånn at vi kunne velge om brukeren skal logge inn med brukernavn eller epost.. tror vi velger brukernavn, og at admin lager dette.. En evt løsning er at vi autogenerer brukernavn ved å ta litt av fornavn og litt av etternavn.. type "chriren" etc...

**Comment by christre42** [comment]
Ja, vi kan vel la admin velge brukernavn nå. Og la brukeren logge inn med det nå. Så kan vi heller gjøre om til versjon 3.
