### ISSUE TITLE
Diskusjon: Bruker session direkte eller via variabel?

### ISSUE THREAD

**Issue by StaaleA** [christre42/Applikasjonsutvikling.github.io#40]
@christre42 @LasseTang 
Driver å jobber en del med session nå, og lurer på hva som er "best practise" når det kommer til å benytte session-variabler. Skal vi bruke de direkte i koden, eller skal vi sette de til $variabler først? Det er jo i teorien det samme, men er det egentlig det? 

Go discussion. Haha.

**Comment by christre42** [comment]
Stemmer for å sette det først! Er ikke det bedre "programmerings-skikk"?

21. mars 2015 kl. 09.36 skrev Ståle Andre <notifications@github.com>:

> @christre42 <https://github.com/christre42> @LasseTang
> <https://github.com/LasseTang>
> Driver å jobber en del med session nå, og lurer på hva som er "best
> practise" når det kommer til å benytte session-variabler. Skal vi bruke de
> direkte i koden, eller skal vi sette de til $variabler først? Det er jo i
> teorien det samme, men er det egentlig det?
>
> Go discussion. Haha.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christre42/Applikasjonsutvikling.github.io/issues/40>.
>



-- 
Mvh Christian Rennemo

**Comment by StaaleA** [comment]
Nja.. Er kanskje enig, men $session er jo i teorien variabler det også... Men kanskje ryddigere å smelle det i en "vanlig" variabel først :) Kan evt høre med gunnar på tirsdag.

**Comment by christre42** [comment]
Ja kanskje det ikke gjelder for $session, vi spør;)
